version: "3"

services:
  database:
    container_name: database
    image: bitnami/postgresql:16
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .docker/database/pg:/bitnami/postgresql
