version: "3"

services:
  pg-admin:
    container_name: pg-admin
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 15432:80
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${PG_USER}
      - POSTGRESQL_PASSWORD=${PG_PASS}
      - POSTGRESQL_DATABASE=${PG_NAME}
    volumes:
      - .docker/pg:/bitnami/postgresql
    ports:
      - ${PG_PORT}:5432

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 127017:8081
    restart: always
    depends_on:
      - mongodb
    environment:
     - ME_CONFIG_BASICAUTH_USERNAME=admin
     - ME_CONFIG_BASICAUTH_PASSWORD=admin
     - ME_CONFIG_MONGODB_SERVER=mongodb
     - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}

  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - .docker/mongo:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=${MONGO_USER}
      - MONGODB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:27017

  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: always
    volumes:
      - .docker/redis:/bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
