version: "3"

services:
  api:
    container_name: api
    build: .
    tty: true
    depends_on:
      - postgresql
      - mongodb
      - kafka
      - redis
    ports:
      - ${HTTP_PORT}:80
      - 9229:9229
    volumes:
      - .:/home/node/app

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${PG_USER}
      - POSTGRESQL_PASSWORD=${PG_PASS}
      - POSTGRESQL_DATABASE=${PG_NAME}
    ports:
      - ${PG_PORT}:5432

  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_ROOT_USER=${MONGO_USER}
      - MONGODB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:27017

  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3200:3000"
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"

volumes:
  grafana-storage:
