version: "3"

services:
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${DB_PORT}:27017
