version: "3"

services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${PG_USER}
      - POSTGRESQL_PASSWORD=${PG_PASS}
      - POSTGRESQL_DATABASE=${PG_NAME}
    volumes:
      - .docker/pg:/bitnami/postgresql
    ports:
      - ${PG_PORT}:5432

  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - .docker/mongo:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=${MONGO_USER}
      - MONGODB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:27017

  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: always
    volumes:
      - .docker/redis:/bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
